name: Live List Search
author: Troy Wolfe
category: Interface
tags: [list, table, search, livesearch]
demo: http://www.consideropen.com/inprogress/livelistsearch/index.html
docs: http://github.com/tr0y/Live-List-Search/blob/0.6/Docs/LiveListSearch.md
current: 0.6